version: 2.1

orbs:
  scala-build: liveintent/scala-build@10.3

parameters:
  ssh_key_fingerprint:
    type: string
    default: "c2:73:84:c4:64:a4:81:69:c6:f3:35:ee:e4:09:bc:6d"
  cache_prefix:
    type: string
    default: v1_java17
  jdk_version:
    type: string
    default: "21"

references:
  any_commit: &any_commit
    tags:
      only: /.*/

  untagged_snapshot: &untagged_commit
    tags:
      only: /^$/

jobs:
  # Parameterized job with localstack container running
  run_with_localstack:
    parameters:
      image:
        default: cimg/openjdk:<< pipeline.parameters.jdk_version >>.0
        type: string
      sbt_command:
        type: string
      resource_class:
        default: large
        type: string
      save_cache:
        default: true
        type: boolean
    docker:
      - image: << parameters.image >>
      - image: localstack/localstack:3.4.0
        environment:
          LOCALSTACK_HOST: localstack
          SERVICES: 'cloudwatch,dynamodb'
          USE_SSL: "false"
          DEFAULT_REGION: 'us-east-1'
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: dummy-key
          AWS_SECRET_ACCESS_KEY: dummy-key
          UPDATE_SHARD_COUNT_DURATION: "10000ms"
          DEBUG: "1"
    resource_class: << parameters.resource_class >>

    steps:
      - attach_workspace:
          at: ~/project
      - scala-build/run_cached:
          command_name: << parameters.sbt_command >>
          command: sbt << parameters.sbt_command >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          save_cache: << parameters.save_cache >>
workflows:
  version: 2
  build:
    jobs:
      - scala-build/compile:
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          name: compile
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          filters: *any_commit

      - run_with_localstack:
          name: lint
          context: org-global
          sbt_command: check
          requires:
            - compile
          filters: *any_commit
      - run_with_localstack:
          name: test213
          context: org-global
          sbt_command: interopFutures/compile core/test interopFutures/test Compile/doc
          save_cache: false
          requires:
            - compile
          filters: *any_commit
      - run_with_localstack:
          name: test213_dynamic_consumer
          context: org-global
          sbt_command: dynamicConsumer/test
          save_cache: false
          requires:
            - compile
          filters: *any_commit

      - scala-build/publish_sbt:
          name: publish_snapshot
          context: org-global
          jdk_version: << pipeline.parameters.jdk_version >>
          cache_prefix: << pipeline.parameters.cache_prefix >>
          requires:
            - lint
            - test213
            - test213_dynamic_consumer
          filters: *untagged_commit
